DOCSUP-33857 Updated docstrings in conditions.py
Toloka/toloka-kit pull request #110
Opened 2022-09-22 15:36 UTC by lehasm

## Description

### Connected issues (if any)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation and examples improvement (changes affected documentation and/or examples)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-09-27 08:06 UTC, alexandervnuchkov requested changes

2022-09-27 08:06 UTC, alexandervnuchkov commented on src/client/conditions.py
> +        * `ACCEPT_AFTER_REJECT` — An assignment with previously set `REJECTED` status was accepted.
...with the previously set...

2022-09-27 08:06 UTC, alexandervnuchkov commented on src/client/conditions.py
> +    `SkillId` provides details if [PoolAccessRevokedReason](toloka.client.conditions.PoolAccessRevokedReason.md) condition equals `SKILL_CHANGE`.
...if the [PoolAccessRevokedReason](toloka.client.conditions.PoolAccessRevokedReason.md) condition...

2022-10-10 16:41 UTC, alexdrydew approved these changes

2022-10-10 16:41 UTC, merged